ftse_100_stocks = {
    'Anglo American plc': 'AAL.L',
    'Associated British Foods plc': 'ABF.L',
    'Admiral Group plc': 'ADM.L',
    'Ashtead Group plc': 'AHT.L',
    'Antofagasta plc': 'ANTO.L',
    'Aviva plc': 'AV..L',
    'AstraZeneca plc': 'AZN.L',
    'BAE Systems plc': 'BA.L',
    'Barclays plc': 'BARC.L',
    'British American Tobacco plc': 'BATS.L',
    'Barratt Developments plc': 'BDEV.L',
    'BHP Group plc': 'BHP.L',
    'BP plc': 'BP.L',
    'Burberry Group plc': 'BRBY.L',
    'BlackRock World Mining Trust plc': 'BRWM.L',
    'BT Group plc': 'BT-A.L',
    'Coca-Cola HBC AG': 'CCH.L',
    'Carnival plc': 'CCL.L',
    'Croda International plc': 'CRDA.L',
    'Cineworld Group plc': 'CINE.L',
    'Compass Group plc': 'CPG.L',
    'CRH plc': 'CRH.L',
    'ConvaTec Group plc': 'CTEC.L',
    'DCC plc': 'DCC.L',
    'Diageo plc': 'DGE.L',
    'Daily Mail and General Trust plc': 'DMGT.L',
    'DS Smith plc': 'SMDS.L',
    'Evraz plc': 'EVR.L',
    'Experian plc': 'EXPN.L',
    'Ferguson plc': 'FERG.L',
    'Fresnillo plc': 'FRES.L',
    'GlaxoSmithKline plc': 'GSK.L',
    'Halma plc': 'HLMA.L',
    'Hargreaves Lansdown plc': 'HL.L',
    'HSBC Holdings plc': 'HSBA.L',
    'International Consolidated Airlines Group SA': 'IAG.L',
    'InterContinental Hotels Group plc': 'IHG.L',
    '3i Group plc': 'III.L',
    'Imperial Brands plc': 'IMB.L',
    'Informa plc': 'INF.L',
    'Intertek Group plc': 'ITRK.L',
    'ITV plc': 'ITV.L',
    'Just Eat Takeaway.com NV': 'JET.L',
    'JD Sports Fashion plc': 'JD.L',
    'Just Eat plc': 'JE.L',
    'Johnson Matthey plc': 'JMAT.L',
    'Kingfisher plc': 'KGF.L',
    'Land Securities Group plc': 'LAND.L',
    'Legal & General Group plc': 'LGEN.L',
    'Lloyds Banking Group plc': 'LLOY.L',
    'London Stock Exchange Group plc': 'LSEG.L',
    'M&G plc': 'MNG.L',
    'Melrose Industries plc': 'MRO.L',
    'Morrison (Wm) Supermarkets plc': 'MRW.L',
    'National Grid plc': 'NG..L',
    'Next plc': 'NXT.L',
    'Ocado Group plc': 'OCDO.L',
    'Pennon Group plc': 'PNN.L',
    'Flutter Entertainment plc': 'PPB.L',
    'Prudential plc': 'PRU.L',
    'Persimmon plc': 'PSN.L',
    'Pearson plc': 'PSON.L',
    'Reckitt Benckiser Group plc': 'RB.L',
    'Royal Dutch Shell plc Class A': 'RDSA.L',
    'Royal Dutch Shell plc Class B': 'RDSB.L',
    'RELX plc': 'REL.L',
    'Rentokil Initial plc': 'RTO.L',
    'Sainsbury (J) plc': 'SBRY.L',
    'Schroders plc': 'SDR.L',
    'Sage Group plc': 'SGE.L',
    'Segro plc': 'SGRO.L',
    'Scottish Mortgage Investment Trust plc': 'SMT.L',
    'Smiths Group plc': 'SMIN.L',
    'Smith & Nephew plc': 'SN..L',
    'Spirax-Sarco Engineering plc': 'SPX.L',
    'SSE plc': 'SSE.L',
    'Standard Chartered plc': 'STAN.L',
    'St. James''s Place plc': 'STJ.L',
    'Severn Trent plc': 'SVT.L',
    'Tesco plc': 'TSCO.L',
    'TUI AG': 'TUI.L',
    'Taylor Wimpey plc': 'TW..L',
    'Unilever plc': 'ULVR.L',
    'United Utilities Group PLC': 'UU.L',
    'Vodafone Group plc': 'VOD.L',
    'Weir Group PLC': 'WEIR.L',
    'Whitbread plc': 'WTB.L',
    'WPP plc': 'WPP.L'
}

stocks = ['AHT.L', 'JD.L', 'MRO.L', 'HLMA.L', 'LSEG.L']