ftse_100_stocks = {
    '3I Group Plc': 'III.L',
    'Abrdn Plc': 'ABDN.L',
    'Admiral Group Plc': 'ADM.L',
    'Airtel Africa Plc': 'AAF.L',
    'Anglo American Plc': 'AAL.L',
    'Antofagasta Plc': 'ANTO.L',
    'Ashtead Group Plc': 'AHT.L',
    'Associated British Foods Plc': 'ABF.L',
    'Astrazeneca Plc': 'AZN.L',
    'Auto Trader Group Plc': 'AUTO.L',
    'Aviva Plc': 'AV.L',
    'B&M European Value Retail S.A.': 'BME.L',
    'Bae Systems Plc': 'BA.L',
    'Barclays Plc': 'BARC.L',
    'Barratt Developments Plc': 'BDEV.L',
    'Beazley Plc': 'BEZ.L',
    'Berkeley Group Holdings (The) Plc': 'BKG.L',
    'BP Plc': 'BP.L',
    'British American Tobacco Plc': 'BATS.L',
    'British Land Co Plc': 'BLND.L',
    'Bt Group Plc': 'BT-A.L',
    'Bunzl Plc': 'BNZL.L',
    'Burberry Group Plc': 'BRBY.L',
    'Centrica Plc': 'CNA.L',
    'Coca-Cola Hbc AG': 'CCH.L',
    'Compass Group Plc': 'CPG.L',
    'Convatec Group Plc': 'CTEC.L',
    'Crh Plc': 'CRH.L',
    'Croda International Plc': 'CRDA.L',
    'DCC Plc': 'DCC.L',
    'Diageo Plc': 'DGE.L',
    'Endeavour Mining Plc': 'EDV.L',
    'Entain Plc': 'ENT.L',
    'Experian Plc': 'EXPN.L',
    'F&C Investment Trust Plc': 'FCIT.L',
    'Flutter Entertainment Plc': 'FLTR.L',
    'Frasers Group Plc': 'FRAS.L',
    'Fresnillo Plc': 'FRES.L',
    'Glencore Plc': 'GLEN.L',
    'Gsk Plc': 'GSK.L',
    'Haleon Plc': 'HLN.L',
    'Halma Plc': 'HLMA.L',
    'Hargreaves Lansdown Plc': 'HL.L',
    'Hiscox Ld': 'HSX.L',
    'Hsbc Hldgs Plc': 'HSBA.L',
    'Imperial Brands Plc': 'IMB.L',
    'Informa Plc': 'INF.L',
    'Intercontinental Hotels Group Plc': 'IHG.L',
    'Intertek Group Plc': 'ITRK.L',
    'Intl Consolidated Airlines Group SA': 'IAG.L',
    'Jd Sports Fashion Plc': 'JD.L',
    'Johnson Matthey Plc': 'JMAT.L',
    'Kingfisher Plc': 'KGF.L',
    'Land Securities Group Plc': 'LAND.L',
    'Legal & General Group Plc': 'LGEN.L',
    'Lloyds Banking Group Plc': 'LLOY.L',
    'London Stock Exchange Group Plc': 'LSEG.L',
    'M&G Plc': 'MNG.L',
    'Melrose Industries Plc': 'MRO.L',
    'Mondi Plc': 'MNDI.L',
    'National Grid Plc': 'NG.L',
    'Natwest Group Plc': 'NWG.L',
    'Next Plc': 'NXT.L',
    'Ocado Group Plc': 'OCDO.L',
    'Pearson Plc': 'PSON.L',
    'Pershing Square Holdings Ltd': 'PSH.L',
    'Persimmon Plc': 'PSN.L',
    'Phoenix Group Holdings Plc': 'PHNX.L',
    'Prudential Plc': 'PRU.L',
    'Reckitt Benckiser Group Plc': 'RKT.L',
    'Relx Plc': 'REL.L',
    'Rentokil Initial Plc': 'RTO.L',
    'Rightmove Plc': 'RMV.L',
    'Rio Tinto Plc': 'RIO.L',
    'Rolls-Royce Holdings Plc': 'RR.L',
    'Rs Group Plc': 'RS1.L',
    'Sage Group Plc': 'SGE.L',
    'Sainsbury(J) Plc': 'SBRY.L',
    'Schroders Plc': 'SDR.L',
    'Scottish Mortgage Inv Tst Plc': 'SMT.L',
    'Segro Plc': 'SGRO.L',
    'Severn Trent Plc': 'SVT.L',
    'Shell Plc': 'SHEL.L',
    'Smith & Nephew Plc': 'SN.L',
    'Smith (Ds) Plc': 'SMDS.L',
    'Smiths Group Plc': 'SMIN.L',
    'Smurfit Kappa Group Plc': 'SKG.L',
    'Spirax-Sarco Engineering Plc': 'SPX.L',
    'SSE Plc': 'SSE.L',
    'St.James\'S Place Plc': 'STJ.L',
    'Standard Chartered Plc': 'STAN.L',
    'Taylor Wimpey Plc': 'TW.L',
    'Tesco Plc': 'TSCO.L',
    'Unilever Plc': 'ULVR.L',
    'Unite Group Plc': 'UTG.L',
    'United Utilities Group Plc': 'UU.L',
    'Vodafone Group Plc': 'VOD.L',
    'Weir Group Plc': 'WEIR.L',
    'Whitbread Plc': 'WTB.L',
    'WPP Plc': 'WPP.L'
}

sp500_stocks = {
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Alphabet": "GOOGL",
    "Amazon": "AMZN",
    "Nvidia": "NVDA",
    "Meta Platforms": "META",
    "Tesla": "TSLA"
}

dax_stocks = {
    "Adidas": "ADS.DE",
    "Airbus Group": "AIR.PA",
    "Allianz": "ALV.DE",
    "BASF": "BAS.DE",
    "Bayer": "BAYN.DE",
    "Beiersdorf AG": "BEI.DE",
    "BMW ST": "BMW.DE",
    "Brenntag AG": "BNR.DE",
    "Continental AG": "CON.DE",
    "Covestro": "1COV.DE",
    "Deutsche Bank AG": "DBK.DE",
    "Deutsche Boerse": "DB1.DE",
    "Deutsche Post": "DHL.DE",
    "Deutsche Telekom AG": "DTE.DE",
    "E.ON SE": "EOAN.DE",
    "Fresenius Medical Care": "FME.DE",
    "Fresenius SE": "FRE.DE",
    "Heidelbergcement": "HEI.DE",
    "Hello Fresh SE": "HFG.DE",
    "Henkel VZO": "HEN3.DE",
    "Infineon": "IFX.DE",
    "Mercedes Benz Group": "MBG.DE",
    "Merck": "MRK.DE",
    "MTU Aero": "MTX.DE",
    "Munich Re Group": "MUV2.DE",
    "Porsche": "PAH3.DE",
    "Puma": "PUM.DE",
    "Qiagen": "QIA.DE",
    "RWE AG ST": "RWE.DE",
    "SAP": "SAP.DE",
    "Sartorius AG VZO": "SRT3.DE",
    "Siemens AG": "SIE.DE",
    "Siemens Energy AG": "ENR.DE",
    "Siemens Healthineers": "SHL.DE",
    "Symrise AG": "SY1.DE",
    "Volkswagen VZO": "VOW3.DE",
    "Vonovia": "VNA.DE",
    "Zalando SE": "ZAL.DE"
}